server:
  port: 8080
  servlet:
    context-path: /sell
    session:
      timeout: 7200s
spring:
  application:
    name: buyer
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/cloud?serverTimezone=GMT%2b8&useSSL=false&characterEncoding=UTF-8
    username: root
    password: root
  jpa:
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  redis:
    host: 127.0.0.1
    port: 6379
    password: sl6819961
  jackson:
    default-property-inclusion: non_null
wechat:
  mpAppId: wx6d790fe13fcf7a82
  mpAppSecret: 8fa58d6612648f4f204362155bdb5210
  mpAppIdTest: wx39e0c2f1b1fdc18c
  mpAppSecretTest: f67c87798f947b9b3687d199f2d169b2
  mchId: 1522963161
  mchKey: 130930199411012418Fan18538111791
  keyPath: /usr/local/developer/cert/apiclient_cert.p12
  notifyUrl: http://www.fkapok.cn/sell/pay/notify
  templateId:
    orderStatus: FIl1dwXx2Doq-MaVJZuQIg_kiyRCUa-HkFzcCosQ2_4
producturl:
  url: http://www.fkapok.cn
swagger:
  show: false

