server:
  port: 8080
  servlet:
    context-path: /sell
spring:
  application:
    name: buyer
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.242.130/cloud?serverTimezone=GMT%2b8&useSSL=false&characterEncoding=UTF-8
    username: root
    password: root
  jpa:
    show-sql: true
  redis:
    host: 192.168.242.130
    port: 6379
    password:
  jackson:
    default-property-inclusion: non_null
wechat:
  mpAppId: wx6d790fe13fcf7a82
  mpAppSecret: 8fa58d6612648f4f204362155bdb5210
  mchId: 1522963161
  mchKey: 130930199411012418Fan18538111791
  keyPath: F:/MyProject/WeiXinShop/buyer/src/main/resources/static/cert/apiclient_cert.p12
  notifyUrl: http://mapok.natapp1.cc/sell/pay/notify

producturl:
  url: http://mapok.natapp1.cc